echo -en "Alacritty\0icon\x1f/usr/share/icons/Papirus/32x32/apps/utilities-terminal.svg\n"
echo -en "Audacity\0icon\x1f/usr/share/icons/Papirus/32x32/apps/audacity.svg\n"
echo -en "btop\0icon\x1f/usr/share/icons/Papirus/32x32/apps/btop.svg\n"
echo -en "Discord\0icon\x1f/usr/share/icons/Papirus/32x32/apps/discord.svg\n"
echo -en "Firefox\0icon\x1f/usr/share/icons/Papirus/32x32/apps/firefox.svg\n"
echo -en "GIMP\0icon\x1f/usr/share/icons/Papirus/32x32/apps/gimp.svg\n"
echo -en "GNumeric\0icon\x1f/usr/share/icons/Papirus/32x32/apps/gnumeric.svg\n"
echo -en "GOverlay\0icon\x1f/usr/share/icons/Papirus/32x32/apps/goverlay.svg\n"
echo -en "GParted\0icon\x1f/usr/share/icons/Papirus/32x32/apps/gparted.svg\n"
echo -en "GThumb\0icon\x1f/usr/share/icons/Papirus/32x32/apps/gthumb.svg\n"
echo -en "HandBrake\0icon\x1f/usr/share/icons/Papirus/32x32/apps/ffmpeg.svg\n"
echo -en "htop\0icon\x1f/usr/share/icons/Papirus/32x32/apps/htop.svg\n"
echo -en "ImageMagick\0icon\x1f/usr/share/icons/Papirus/32x32/apps/image-viewer.svg\n"
echo -en "Kdenlive\0icon\x1f/usr/share/icons/Papirus/32x32/apps/kdenlive.svg\n"
echo -en "Kick - Destiny\0icon\x1f/usr/share/icons/Papirus/32x32/apps/video-player.svg\n"
echo -en "Kodi\0icon\x1f/usr/share/icons/Papirus/32x32/apps/kodi.svg\n"
echo -en "LibreOffice Writer\0icon\x1f/usr/share/icons/Papirus/32x32/apps/libreoffice7.2-writer.svg\n"
echo -en "Lossless Cut\0icon\x1f/usr/share/icons/Papirus/32x32/apps/losslesscut.svg\n"
echo -en "MakeMKV\0icon\x1f/usr/share/icons/Papirus/32x32/apps/makemkv.svg\n"
echo -en "Minecraft Launcher\0icon\x1f/usr/share/icons/Papirus/32x32/apps/minecraft-launcher.svg\n"
echo -en "Mousepad\0icon\x1f/usr/share/icons/Papirus/32x32/apps/mousepad.svg\n"
echo -en "mpv\0icon\x1f/usr/share/icons/Papirus/32x32/apps/mpv.svg\n"
echo -en "NMIXX\0icon\x1f/usr/share/icons/Papirus/32x32/apps/reddit.svg\n"
echo -en "OBS\0icon\x1f/usr/share/icons/Papirus/32x32/apps/obs.svg\n"
echo -en "Puddletag\0icon\x1f/usr/share/icons/Papirus/32x32/apps/puddletag.svg\n"
echo -en "qalc\0icon\x1f/usr/share/icons/Papirus/32x32/apps/qalculate.svg\n"
echo -en "qBittorrent\0icon\x1f/usr/share/icons/Papirus/32x32/apps/qbittorrent.svg\n"
echo -en "Ristretto\0icon\x1f/usr/share/icons/Papirus/32x32/apps/ristretto.svg\n"
echo -en "Rofi\0icon\x1f/usr/share/icons/Papirus/32x32/apps/launch.svg\n"
echo -en "Rumble - Destiny\0icon\x1f/usr/share/icons/Papirus/32x32/apps/video-player.svg\n"
echo -en "Shuffle Playlist\0icon\x1f/usr/share/icons/Papirus/32x32/apps/musicbrainz.svg\n"
echo -en "Steam\0icon\x1f/usr/share/icons/Papirus/32x32/apps/steam.svg\n"
echo -en "Surf\0icon\x1f/usr/share/icons/Papirus/32x32/apps/web-browser.svg\n"
echo -en "Thunar\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.thunar.svg\n"
echo -en "Twitter - Destiny\0icon\x1f/usr/share/icons/Papirus/32x32/apps/twitter.svg\n"
echo -en "VSCode\0icon\x1f/usr/share/icons/Papirus/32x32/apps/code.svg\n"
echo -en "WiFi Hotspot\0icon\x1f/usr/share/icons/Papirus/32x32/apps/wifi-radar.svg\n"
echo -en "Xfce About\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.about.svg\n"
echo -en "Xfce Appearance\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.settings.appearance.svg\n"
echo -en "Xfce Appfinder\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.appfinder.svg\n"
echo -en "Xfce Keyboard Settings\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.settings.keyboard.svg\n"
echo -en "Xfce Screenshooter\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.screenshooter.svg\n"
echo -en "Xfce Settings Manager\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.settings.manager.svg\n"
echo -en "Xfce Taskmanager\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.taskmanager.svg\n"
echo -en "Xfce Terminal\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.terminal.svg\n"
echo -en "Xfce Tweaks Settings\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.xfwm4-tweaks.svg\n"
echo -en "Xfwm Settings\0icon\x1f/usr/share/icons/Papirus/32x32/apps/org.xfce.xfwm4.svg\n"
echo -en "Zathura\0icon\x1f/usr/share/icons/Papirus/32x32/apps/zathura.svg\n"
