[colors.bright]
black = "#7a71aa"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79d2"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f1"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#22212d"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#22212d"
blue = "#9a7cff"
cyan = "#38ffea"
green = "#52ff6d"
magenta = "#ff76c1"
red = "#e64747"
white = "#f8f8f1"
yellow = "#ffff80"

[colors.primary]
background = "#22212d"
bright_foreground = "#ffffff"
foreground = "#f8f8f1"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
shape = "Beam"

[env]
WINIT_X11_SCALE_FACTOR = "2"

[font]
size = 6

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[window]
dynamic_padding = true
#dynamic_title = false

[window.dimensions]
columns = 100
lines = 25

# https://mitjafelicijan.com/alacritty-open-links-with-modifier.html
[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0019"
key = "z"
mods = "Control|Shift"
