[colors.bright]
black = "0x5a647e"
blue = "0x6d9cbe"
cyan = "0x519f50"
green = "0xa5c261"
magenta = "0xb6b3eb"
red = "0xda4939"
white = "0xf9f7f3"
yellow = "0xffc66d"

[colors.normal]
black = "0x2b2b2b"
blue = "0x6d9cbe"
cyan = "0x519f50"
green = "0xabce59"
magenta = "0xb6b3eb"
red = "0xda4939"
white = "0xe6e1dc"
yellow = "0xffc66d"

[colors.primary]
background = "0x2b2b2b"
foreground = "0xe6e1dc"

[cursor.style]
shape = "Beam"

[font]
size = 7

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[window.dimensions]
columns = 100
lines = 25
